creation_rules:
  - encrypted_regex: '^[A-Z0-9_]+$'
    age: >-
      age19662lp3r7w35uhau8ehdmtx0d5ae958kz5dj0v2ln3skulmv2dns4hq4hx,
      age1ma4mrxyp0jnkkes8qyykk7uxs5jtfvr0sllc8l762sh2lgs0rezqzpsyjx,
      age1cu4cgkkfpg8rrd7quhrvt2uvzpqht7k4jhq2ecfjnsd3v9v334eq4fz5yu,
      age17ssmnrtnzum8fhux7ptt7386xxawkvkqzhrfw8znftsek692fygqha9jdx,
      age12f8fhu02sl08padsvgj0cpz2untp9pma8txf7zeplwel9dsuwyus9t33rx,
      age1nuqszckzxhzpryc3jppm3qxhkydmzem0q34r8k9qukgp77dv2euq9hfah2,
      age13s2dtkhmdkrmrdkhv3vvtl909ssn366fwhrllv9eej6nzxj7yqtq78symf,
      age1ya6nzu23n0rhe72v7v8clxj4vgplfxqwf2qg3u0ay53puge9ec6s2kywy6,
      age1rnc30n6j4rn00awqeezlzpkcz3rzaazlj66wyv2x6md48u9fxy9q7yk7um
